# Generated by Django 4.1 on 2022-08-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antonym',
            old_name='definition_id',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='word_id',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='definition_id',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='synonym',
            old_name='definition_id',
            new_name='definition',
        ),
    ]
